AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Visual Express for Lambda
Resources:
  VisualExpress:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: vxpress-config.start
      Timeout: 10
      CodeUri: .
